# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - develop
  - release/*
  - master
variables:
  BRANCH_NAME: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
stages:
  - stage: transpile
    displayName: Transpile Templates
    jobs:
      - job: transpile
        displayName: Transpile Templates
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: mvn --version
            displayName: 'Run a one-line script'
  - stage: merge
    displayName: Merge Templates
    jobs:
      - job: merge
        displayName: Merge Templates
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: echo mvn clean compile org.codehaus.mojo:exec-maven-plugin:3.0.0:java
            displayName: 'Run a one-line script'
  - stage: publish
    displayName: Publish Templates
    jobs:
      - job: publish
        displayName: Publish Templates
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            persistCredentials: true
            fetchDepth: 0
          - script: mvn clean compile org.codehaus.mojo:exec-maven-plugin:3.0.0:java
            displayName: Publish Templates
          - script: |
              git config user.name "mario.tema"
              git config user.email "mario.tema@ascent.io"
              git checkout $(BRANCH_NAME) --
              git add --all
              git commit -m "DX-1000 Update Docu within build-id: $(Build.BuildId)"
              git push origin $(BRANCH_NAME)
            displayName: Git Commit
