# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - develop
  - release/*
  - master
variables:
  systemName: DCS Doc-as-Code
  version: 1.0.0-SNAPSHOT
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  isRelease: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')]
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
stages:
  - stage: initialize
    displayName: Initialize
    jobs:
      - job: initialize
        displayName: Initialize
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: mvn --version
            displayName: 'Run a one-line script'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              goals: 'clean'